services:
  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: apidb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
